quip/quip-apps

- examples/stock-price/README.md
- examples/stock-price/app/manifest.json
- examples/stock-price/package-lock.json
- examples/stock-price/package.json
- examples/stock-price/src/App.js
- examples/stock-price/src/App.less
- examples/stock-price/src/components/Dialog/Dialog.js
- examples/stock-price/src/components/Dialog/Dialog.less
- examples/stock-price/src/components/Link/Link.js
- examples/stock-price/src/components/PriceChart/PriceChart.js
- examples/stock-price/src/model.js
- examples/stock-price/src/root.jsx
- examples/stock-price/webpack.config.js
This will soon be published on AppExchange too.
Data provider is IEX (see terms of use here: https://iextrading.com/api-terms/ )
Charts created using ChartJS.
> Added Stock Price live app example

- packages/quip-apps-api/src/client.ts
removeEventListener(
type: ElementsEventType | EventType,
listener: () => void
) {}
> Make removeEventListener type match quip

- packages/quip-cli/README.md
- packages/quip-cli/package-lock.json
- packages/quip-cli/package.json
- packages/quip-cli/src/commands/init.ts
- packages/quip-cli/src/commands/migration.ts
- packages/quip-cli/src/lib/manifest.ts
- packages/quip-cli/src/lib/types.ts
- packages/quip-cli/src/lib/util.ts
- packages/quip-cli/templates/migration.example.js
Also adds a few utilities for messing with manifest.json files
> Add "qla migration" command

- .github/workflows/tests.yml
- package-lock.json
- package.json
- packages/quip-cli/.mocharc.json
- packages/quip-cli/jest.config.js
- packages/quip-cli/package-lock.json
- packages/quip-cli/package.json
- packages/quip-cli/test/__snapshots__/migration.test.ts.snap
- packages/quip-cli/test/fixtures/migration/manifest.json
- packages/quip-cli/test/migration.test.ts
- packages/quip-cli/test/tsconfig.json
- Adds jest tests & coverage to the quip-cli tool
- Adds a workflow for running all the tests
> Jest tests

- .github/workflows/publish.yml
- .github/workflows/tests.yml
This PR adds an action that publishes new commits to master under the `next` tag.
> Publish to npm github action

- packages/quip-cli/templates/js_webpack/src/components/main.jsx
- packages/quip-cli/templates/js_webpack/src/model/root.js
- packages/quip-cli/templates/ts_webpack/src/components/main.tsx
- packages/quip-cli/templates/ts_webpack/src/model/root.ts
> Remove model's static DATA_VERSION field

- .github/workflows/publish.yml
- .github/workflows/tests.yml
- run tests before publishing
- run package-specific tests in their own jobs
> Rework some actions

- .github/workflows/tests.yml
- packages/quip-cli/package-lock.json
- packages/quip-cli/test/login.test.ts
- packages/quip-test-utils/package-lock.json
- packages/quip-test-utils/package.json
Attempt to fix broken actions on master
> More Actions Fixes

- packages/quip-apps-api/src/rich-text-record.ts
related to https://github.com/quip/quip/pull/8275
> add listenToSave in rich-text-record mock

- packages/quip-cli/README.md
- packages/quip-cli/package-lock.json
- packages/quip-cli/package.json
- packages/quip-cli/src/commands/apps.ts
- packages/quip-cli/src/commands/bump.ts
- packages/quip-cli/src/commands/init.ts
- packages/quip-cli/src/commands/login.ts
- packages/quip-cli/src/commands/migration.ts
- packages/quip-cli/src/commands/publish.ts
- packages/quip-cli/src/index.ts
- packages/quip-cli/src/lib/cli-api.ts
- packages/quip-cli/src/lib/config.ts
- packages/quip-cli/src/lib/manifest.ts
- packages/quip-cli/src/lib/print.ts
- packages/quip-cli/src/lib/types.ts
- packages/quip-cli/src/lib/util.ts
- packages/quip-cli/test/lib/util.test.ts
- packages/quip-cli/test/login.test.ts
- packages/quip-test-utils/package-lock.json
Adds a few commands:
- apps:
- list, select, view apps and app versions
- create new apps
- publish:
- push a local build to the console
- bump:
- bump version numbers on a local repo
> qla publish, bump, & apps

- README.md
These docs are fairly accurate, and I dropped sections that are no longer relevant or yet to be clearly defined (e.g. publishing). Could use more, but don't want to spend too much time on this until we know what our official documentation updates will look like as well, since we should be able to mostly just link to them.
> Update Readme with some imperfect but less bad information

- packages/quip-cli/package-lock.json
- packages/quip-cli/package.json
- packages/quip-cli/src/commands/login.ts
- packages/quip-cli/src/lib/cli-api.ts
- packages/quip-cli/test/login.test.ts
Self explanatory - this should be good for prod
> Switch login flow to the new PKCE flow

- .github/workflows/tests.yml
- packages/quip-test-utils/package.json
- packages/quip-test-utils/tsconfig.json
Attempting to get tests to work in CI over here
> Iterate test fixes

- .github/workflows/publish.yml
- package.json
Check out latest non-@next tag and publish it in addition to the @next tag
Validating basic parsing on this PR then will iterate on master
> Move publishing logic & commands to github actions

- package-lock.json
- package.json
- packages/Chevron/package-lock.json
- packages/create-quip-app/package-lock.json
- packages/handleRichTextBoxKeyEventNavigation/package-lock.json
- packages/quip-apps-api/package-lock.json
- packages/quip-apps-compat/package-lock.json
- packages/quip-cli/package-lock.json
- packages/quip-test-utils/package-lock.json
- packages/quiptext/package-lock.json
- packages/webpack-config/package-lock.json
> NPM audit fix

- packages/quip-apps-api/src/user.ts
Corresponding change to https://github.com/quip/quip/pull/9792.
> Add company ID to the live apps user object

- packages/quip-apps-api/src/user.ts
We want the mocked values to be clearly not real data (see https://github.com/quip/quip-apps/pull/141/files#r520952743).
> Update mock User.getCompanyId() value

- packages/quip-apps-api/src/auth.ts
- packages/quip-apps-api/src/base-oauth.ts
- allow not passing params
- constrain params
> Fix auth login type

- packages/quip-cli/src/commands/publish.ts
Add an md5 field that represents all the uploaded files when publishing
> Bundle md5s

- packages/quip-cli/src/commands/apps.ts
- packages/quip-cli/src/lib/cli-api.ts
- Change "development" to "beta" for clarity, change icon
- Fix types and crash related to apps not having a release version
- Include build number in output
> Fix up the Apps command

- packages/quip-cli/README.md
- packages/quip-cli/src/commands/init.ts
- packages/quip-cli/src/commands/publish.ts
- packages/quip-cli/src/commands/release.ts
- packages/quip-cli/src/lib/cli-api.ts
- packages/quip-cli/templates/js_webpack/manifest.json
- packages/quip-cli/templates/ts_webpack/manifest.json
Add ability to release from the command line
> CLI Release

- packages/quip-apps-api/src/client.ts
> edit signature for mobile command support

- packages/quip-apps-api/src/client.ts
https://github.com/quip/issues/issues/17162
> add setPayload to quip-apps-api

- examples/salesforce-lightning-design-system/webpack.config.js
- packages/quip-cli/templates/js_webpack/webpack.config.js
- packages/quip-cli/templates/ts_webpack/webpack.config.js
- packages/webpack-config/webpack.config.js
https://github.com/quip/issues/issues/17121
Note: Will need to update package.json's quip-apps-webpack-config to use the latest version for each of the examples
> add Access-Controller-Allow-Origin header to webpack devServer

- packages/quip-cli/src/lib/manifest.ts
Noticed when troubleshooting something else that some apps have multiple manifest.json files and the current strategy would prefer whichever came first rather than whichever was closest.
Also converges the strategy with existing recursive searching and omits node_modules from the search
> Prefer manifest.json files that are closest to the root
